#!bin/sh

source $ZSH_CONFIG_DIR/anyenv.zsh
source $ZSH_CONFIG_DIR/exports.zsh
source $ZSH_CONFIG_DIR/exports.zsh
source $ZSH_CONFIG_DIR/alias.zsh
source $ZSH_CONFIG_DIR/fzf.zsh
source $ZSH_CONFIG_DIR/zplug.zsh

autoload -Uz colors
colors
PROMPT="%{$fg[cyan]%}%/#%{$reset_color%} %"

# show branch name on left the side
autoload -Uz vcs_info
zstyle ':vcs_info:*' formats '(%s)[%b]'
zstyle ':vcs_info:*' actionformats '(%s)[%b|%a]'
precmd () { vcs_info }
setopt prompt_subst
RPROMPT=$RPROMPT'${vcs_info_msg_0_}'

HISTFILE=~/.zsh_history
HISTSIZE=10000000
SAVEHIST=10000000
setopt hist_ignore_dups
