# --------------------------------
# -- General
# --------------------------------
unbind-key C-b
set -g prefix C-t
bind-key C-t send-prefix

set-option -g default-shell /bin/zsh

unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded Config!"

set -g default-terminal "screen-256color"
set -g default-command "${SHELL}"

set -q -g status-utf8 on # expect UTF-8 (tmux < 2.2)
setw -q -g utf8 on

set -g base-index 1
set -g pane-base-index 1

set -g history-limit 5000000

# --------------------------------
# -- Display
# --------------------------------
set -g set-titles on
set -g automatic-rename on
set -g automatic-rename-format '#{pane_current_path}'

set -g display-panes-time 800
set -g display-time 1000

setw -g automatic-rename on
set -g renumber-windows on

setw -g monitor-activity on
setw -g visual-activity on
setw -g aggressive-resize on

set -g bell-action any

set -g status on
set -g status-interval 10
set -g status-bg "colour238"
set -g status-fg "colour255"
set -g status-left-length 100
set -g status-right-length 70
set -g status-left "#[fg=colour255,bg=colour241]S: #S #[default]"
set -g status-right "#[fg=colour255,bg=colour241] #h | CPU: #{cpu_icon} #{cpu_percentage} | Batt: #{battery_icon_status} #{battery_percentage} | %m/%d %H:%M:%S#[default]"
set -g status-interval 1
set -g status-keys vi
setw -g window-status-format " #I: #W "
setw -g window-status-current-format "#[fg=colour255,bg=colour25,bold] #I: #W #[default]"

# --------------------------------
# -- Navigation
# --------------------------------
setw -g mode-keys vi
bind -T copy-mode-vi I send -X start-of-line
bind -T copy-mode-vi C-v send -X rectangle-toggle
# unbind -T copy-mode-vi C-v

set -g mouse on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key -r C-h resize-pane -L 5
bind-key -r C-j resize-pane -D 5
bind-key -r C-k resize-pane -U 5
bind-key -r C-l resize-pane -R 5

bind n new-window -c "#{pane_current_path}"
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

bind Enter copy-mode # enter copy mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

set -g popup-style "bg=#1f2335"
set -g popup-border-style "fg=#3b4261,bg=#1f2335"
set -g popup-border-lines rounded
bind-key a run-shell 'tmux popup -d #{pane_current_path} -T "Select a tmux session" -w 60% -h 30% -E "source ~/.zshrc.d/function.zsh && tses || true"'
bind-key A run-shell 'tmux popup -d #{pane_current_path} -T "Select a repository from ghq" -w 60% -h 30% -E "source ~/.zshrc.d/function.zsh && ghqcd || true"'

bind-key R run-shell 'tmux send-keys "cd #{session_path}" Enter'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'hiroppy/tmux-agent-sidebar'

## tmux-agent-sidecar
set -g @sidebar_key "e"
set -g @sidebar_width "50"
set -g @sidebar_activity_lines 10
set -g @sidebar_prompt_lines 5
set -g @sidebar_auto_create off

run '~/.tmux/plugins/tpm/tpm'
