setopt auto_cd
setopt auto_pushd

setopt extended_glob
setopt globdots
setopt brace_ccl
setopt mark_dirs

setopt no_beep

source $HOME/.zshrc.d/history.zsh
source $HOME/.zshrc.d/completion.zsh
source $HOME/.zshrc.d/export.zsh
source $HOME/.zshrc.d/alias.zsh
source $HOME/.zshrc.d/function.zsh
source $HOME/.zshrc.d/theme.zsh
source $HOME/.zshrc.d/plugin.zsh
source $HOME/.zshrc.d/tools.zsh
